# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: graph.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'graph.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgraph.proto\x12\x05graph\"\x1d\n\x05Point\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"E\n\x0bPathRequest\x12\x1b\n\x05start\x18\x01 \x01(\x0b\x32\x0c.graph.Point\x12\x19\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x0c.graph.Point\"1\n\x0cPathResponse\x12!\n\x0bpath_points\x18\x01 \x03(\x0b\x32\x0c.graph.Point2A\n\x0bPathService\x12\x32\n\x07GetPath\x12\x12.graph.PathRequest\x1a\x13.graph.PathResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_POINT']._serialized_start=22
  _globals['_POINT']._serialized_end=51
  _globals['_PATHREQUEST']._serialized_start=53
  _globals['_PATHREQUEST']._serialized_end=122
  _globals['_PATHRESPONSE']._serialized_start=124
  _globals['_PATHRESPONSE']._serialized_end=173
  _globals['_PATHSERVICE']._serialized_start=175
  _globals['_PATHSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
